export const GET_GAME_FETCH = 'GET_GAME_FETCH';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_ERROR = 'GET_GAME_ERROR';
export const START_GAME_SUCCESS = 'START_GAME_SUCCESS';
export const START_GAME_FETCH = 'START_GAME_FETCH';
export const START_GAME_ERROR = 'START_GAME_ERROR';
