export const GET_ROOM_FETCH = 'GET_ROOM_FETCH';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_ERROR = 'GET_ROOM_ERROR';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const CREATE_ROOM_FETCH = 'CREATE_ROOM_FETCH';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';
